fix: strictly validate the contents of version.txt (#769)
Make sure the version tag read from version.txt is a valid semantic version
string.  This PR also renames the env var to `VERSION` to be consistent
with uppercase env var casing used elsewhere in the project.

diff --git a/.github/workflows/get-version/action.yml b/.github/workflows/get-version/action.yml
--- a/.github/workflows/get-version/action.yml
+++ b/.github/workflows/get-version/action.yml
@@ -16,25 +16,31 @@ runs:
       if: inputs.is-tagged == 'false' && startsWith(github.head_ref, 'release-please--')
       env:
         GITHUB_HEAD_REF: ${{ github.head_ref }}
-      run: echo "version=$GITHUB_HEAD_REF" >> $GITHUB_ENV
+      run: echo "VERSION=$GITHUB_HEAD_REF" >> $GITHUB_ENV
       shell: bash
 
     - name: Get version, perform release of tag
       if: inputs.is-tagged == 'true'
-      run: echo "version=v$(cat version.txt)" >> $GITHUB_ENV
+      run: |
+        VERSION="$(tr -d '\n\r' < version.txt)"
+        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "::error::Invalid version format in version.txt: '$VERSION'"
+          exit 1
+        fi
+        echo "VERSION=v${VERSION}" >> $GITHUB_ENV
       shell: bash
 
     - name: Wait for ref to exist
       if: inputs.is-tagged == 'true'
-      run: ./.github/workflows/scripts/wait-for-ref.sh "${version}"
+      run: ./.github/workflows/scripts/wait-for-ref.sh "${VERSION}"
       shell: bash
 
     - name: Fail if no version set
-      if: env.version == ''   
+      if: env.VERSION == ''   
       run: exit 1
       shell: bash
 
     - name: Output version
       id: output-version
-      run: echo "version=${version}" >> $GITHUB_OUTPUT
+      run: echo "version=${VERSION}" >> $GITHUB_OUTPUT
       shell: bash
